import { registerAs } from '@nestjs/config';

export const storageConfig = registerAs('storage', () => ({
  bucket: process.env.R2_BUCKET,
}));

export const STORAGE_BUCKET_TOKEN = 'STORAGE_BUCKET';

export const STORAGE_FOLDERS = {
  AVATARS: 'avatars',

  PATIENT_PHOTOS: 'patient-photos',

  DOCUMENTS: 'documents',

  POST_SURGICAL: 'post-surgical',

  REPORT: 'report',

  SIGNATURES: 'signatures',

  STAMPS: 'stamps',

  HEADERS: 'headers',

  WHATSAPP_TMP: 'whatsapp-tmp',

  PDFS: 'pdfs',

  WHATSAPP_DOWNLOADS: 'whatsapp-downloads',
} as const;

export const STORAGE_FOLDER_TTL: Record<string, number> = {
  [STORAGE_FOLDERS.DOCUMENTS]: 15 * 60,
  [STORAGE_FOLDERS.POST_SURGICAL]: 15 * 60,
  [STORAGE_FOLDERS.SIGNATURES]: 60 * 60,
  [STORAGE_FOLDERS.STAMPS]: 60 * 60,
  [STORAGE_FOLDERS.REPORT]: 60 * 60,
  [STORAGE_FOLDERS.AVATARS]: 24 * 60 * 60,
  [STORAGE_FOLDERS.PATIENT_PHOTOS]: 60 * 60,
  [STORAGE_FOLDERS.HEADERS]: 24 * 60 * 60,
  [STORAGE_FOLDERS.WHATSAPP_TMP]: 10 * 60,
  [STORAGE_FOLDERS.PDFS]: 60 * 60,
  [STORAGE_FOLDERS.WHATSAPP_DOWNLOADS]: 10 * 60,
};

export const STORAGE_FOLDER_CACHE_CONTROL: Record<string, string> = {
  [STORAGE_FOLDERS.PATIENT_PHOTOS]: `private, max-age=${STORAGE_FOLDER_TTL[STORAGE_FOLDERS.PATIENT_PHOTOS] / 2}`,
};

export const STORAGE_FOLDER_SIZE_LIMITS: Record<string, number> = {
  [STORAGE_FOLDERS.DOCUMENTS]: 50 * 1024 * 1024,
  [STORAGE_FOLDERS.POST_SURGICAL]: 50 * 1024 * 1024,
  [STORAGE_FOLDERS.WHATSAPP_TMP]: 10 * 1024 * 1024,
  [STORAGE_FOLDERS.REPORT]: 50 * 1024 * 1024,
  [STORAGE_FOLDERS.HEADERS]: 2 * 1024 * 1024,
  [STORAGE_FOLDERS.AVATARS]: 2 * 1024 * 1024,
  [STORAGE_FOLDERS.PATIENT_PHOTOS]: 2 * 1024 * 1024,
  [STORAGE_FOLDERS.SIGNATURES]: 500 * 1024,
  [STORAGE_FOLDERS.STAMPS]: 500 * 1024,
  [STORAGE_FOLDERS.PDFS]: 10 * 1024 * 1024,
  [STORAGE_FOLDERS.WHATSAPP_DOWNLOADS]: 10 * 1024 * 1024,
};

export const MAX_STORAGE_FILE_SIZE = Math.max(
  ...Object.values(STORAGE_FOLDER_SIZE_LIMITS),
);
