export * from './parser.types';
export * from './cpf.parser';
export * from './cnpj.parser';
export * from './crm.parser';
export * from './tuss.parser';
export * from './cid.parser';
export * from './date.parser';
export * from './phone.parser';
export * from './money.parser';
