import { MigrationInterface, QueryRunner } from "typeorm";

export class AddGlobalAndDoctorIdToBusinessEntities1769315996812 implements MigrationInterface {
    name = 'AddGlobalAndDoctorIdToBusinessEntities1769315996812'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "doctor_profile" DROP CONSTRAINT "FK_doctor_profile_user"`);
        await queryRunner.query(`ALTER TABLE "team_member" DROP CONSTRAINT "FK_team_member_collaborator"`);
        await queryRunner.query(`ALTER TABLE "team_member" DROP CONSTRAINT "FK_team_member_doctor"`);
        await queryRunner.query(`ALTER TABLE "recovery_code" DROP CONSTRAINT "FK_recovery_code_user"`);
        await queryRunner.query(`ALTER TABLE "patient" DROP CONSTRAINT "FK_patient_health_plan"`);
        await queryRunner.query(`ALTER TABLE "patient" DROP CONSTRAINT "FK_patient_doctor"`);
        await queryRunner.query(`ALTER TABLE "surgery_request_quotation" DROP CONSTRAINT "FK_surgery_request_quotation_supplier"`);
        await queryRunner.query(`ALTER TABLE "surgery_request_quotation" DROP CONSTRAINT "FK_surgery_request_quotation_request"`);
        await queryRunner.query(`ALTER TABLE "opme_item" DROP CONSTRAINT "FK_opme_item_request"`);
        await queryRunner.query(`ALTER TABLE "surgery_request_procedure" DROP CONSTRAINT "FK_surgery_request_procedure_procedure"`);
        await queryRunner.query(`ALTER TABLE "surgery_request_procedure" DROP CONSTRAINT "FK_surgery_request_procedure_request"`);
        await queryRunner.query(`ALTER TABLE "document" DROP CONSTRAINT "FK_document_creator"`);
        await queryRunner.query(`ALTER TABLE "document" DROP CONSTRAINT "FK_document_request"`);
        await queryRunner.query(`ALTER TABLE "status_update" DROP CONSTRAINT "FK_status_update_request"`);
        await queryRunner.query(`ALTER TABLE "surgery_request" DROP CONSTRAINT "FK_surgery_request_cid"`);
        await queryRunner.query(`ALTER TABLE "surgery_request" DROP CONSTRAINT "FK_surgery_request_health_plan"`);
        await queryRunner.query(`ALTER TABLE "surgery_request" DROP CONSTRAINT "FK_surgery_request_hospital"`);
        await queryRunner.query(`ALTER TABLE "surgery_request" DROP CONSTRAINT "FK_surgery_request_patient"`);
        await queryRunner.query(`ALTER TABLE "surgery_request" DROP CONSTRAINT "FK_surgery_request_created_by"`);
        await queryRunner.query(`ALTER TABLE "surgery_request" DROP CONSTRAINT "FK_surgery_request_doctor"`);
        await queryRunner.query(`ALTER TABLE "chat_message" DROP CONSTRAINT "FK_chat_message_sender"`);
        await queryRunner.query(`ALTER TABLE "chat_message" DROP CONSTRAINT "FK_chat_message_chat"`);
        await queryRunner.query(`ALTER TABLE "chat" DROP CONSTRAINT "FK_chat_user"`);
        await queryRunner.query(`ALTER TABLE "chat" DROP CONSTRAINT "FK_chat_request"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_notification_user"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP CONSTRAINT "FK_user_notification_settings_user"`);
        await queryRunner.query(`ALTER TABLE "default_document_clinic" DROP CONSTRAINT "FK_default_document_clinic_creator"`);
        await queryRunner.query(`ALTER TABLE "default_document_clinic" DROP CONSTRAINT "FK_default_document_clinic_doctor"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_doctor_profile_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_team_member_doctor_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_team_member_collaborator_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_patient_doctor_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_surgery_request_doctor_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_surgery_request_patient_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_surgery_request_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_surgery_request_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notification_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notification_read"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_role"`);
        await queryRunner.query(`ALTER TABLE "team_member" DROP CONSTRAINT "UQ_team_member_doctor_collaborator"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP COLUMN "email_new_request"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP COLUMN "email_status_change"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP COLUMN "email_new_document"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP COLUMN "email_new_message"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP COLUMN "email_deadline_reminder"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP COLUMN "push_new_request"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP COLUMN "push_status_change"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP COLUMN "push_new_document"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP COLUMN "push_new_message"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP COLUMN "push_deadline_reminder"`);
        await queryRunner.query(`ALTER TABLE "hospital" ADD "is_global" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "hospital" ADD "doctor_id" integer`);
        await queryRunner.query(`ALTER TABLE "health_plan" ADD "is_global" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "health_plan" ADD "doctor_id" integer`);
        await queryRunner.query(`ALTER TABLE "supplier" ADD "is_global" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "supplier" ADD "doctor_id" integer`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD "email_notifications" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD "sms_notifications" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD "push_notifications" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD "new_surgery_request" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD "status_update" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD "pendencies" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD "expiring_documents" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD "weekly_report" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TYPE "public"."subscription_status_enum" RENAME TO "subscription_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."doctor_profile_subscription_status_enum" AS ENUM('trial', 'active', 'expired', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "doctor_profile" ALTER COLUMN "subscription_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "doctor_profile" ALTER COLUMN "subscription_status" TYPE "public"."doctor_profile_subscription_status_enum" USING "subscription_status"::"text"::"public"."doctor_profile_subscription_status_enum"`);
        await queryRunner.query(`ALTER TABLE "doctor_profile" ALTER COLUMN "subscription_status" SET DEFAULT 'trial'`);
        await queryRunner.query(`DROP TYPE "public"."subscription_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "opme_item" ALTER COLUMN "quantity" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "procedure" ALTER COLUMN "active" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "surgery_request_procedure" ALTER COLUMN "quantity" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP CONSTRAINT "UQ_user_notification_settings_user_id"`);
        await queryRunner.query(`ALTER TABLE "team_member" ADD CONSTRAINT "UQ_356f4a7aeeb5ce1082b270ca89f" UNIQUE ("doctor_id", "collaborator_id")`);
        await queryRunner.query(`ALTER TABLE "doctor_profile" ADD CONSTRAINT "FK_5b83901268e3a3d2685d5bf1608" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_member" ADD CONSTRAINT "FK_229ae139290e39e857e21a15aa2" FOREIGN KEY ("doctor_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_member" ADD CONSTRAINT "FK_6732819d5af4c890b00358c9d54" FOREIGN KEY ("collaborator_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recovery_code" ADD CONSTRAINT "FK_f5c95d9ca2047afa670093e2028" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient" ADD CONSTRAINT "FK_e10105a04a8a381baec6ba1fc6a" FOREIGN KEY ("doctor_id") REFERENCES "doctor_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient" ADD CONSTRAINT "FK_26dc362e81bf397fdf72640df5c" FOREIGN KEY ("health_plan_id") REFERENCES "health_plan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery_request_quotation" ADD CONSTRAINT "FK_c16e2628da64778fcc94054d03c" FOREIGN KEY ("surgery_request_id") REFERENCES "surgery_request"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery_request_quotation" ADD CONSTRAINT "FK_75bf89ae1720acf14bd45cf11c6" FOREIGN KEY ("supplier_id") REFERENCES "supplier"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opme_item" ADD CONSTRAINT "FK_01965849109def09d33400fbd9f" FOREIGN KEY ("surgery_request_id") REFERENCES "surgery_request"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery_request_procedure" ADD CONSTRAINT "FK_d9c453a21e06a38434e421ebcdc" FOREIGN KEY ("surgery_request_id") REFERENCES "surgery_request"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery_request_procedure" ADD CONSTRAINT "FK_5f62cc1131ccead5434ab04ddde" FOREIGN KEY ("procedure_id") REFERENCES "procedure"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document" ADD CONSTRAINT "FK_6ed807dd011acbee547ca95e5ac" FOREIGN KEY ("surgery_request_id") REFERENCES "surgery_request"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document" ADD CONSTRAINT "FK_d8538de16919357e4cd0351d0bd" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "status_update" ADD CONSTRAINT "FK_f8390fe2c05188bbe4961f835b9" FOREIGN KEY ("surgery_request_id") REFERENCES "surgery_request"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery_request" ADD CONSTRAINT "FK_b7e705594f01025afe9cb04502c" FOREIGN KEY ("doctor_id") REFERENCES "doctor_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery_request" ADD CONSTRAINT "FK_345285cea966c1f78d2096e02b2" FOREIGN KEY ("created_by_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery_request" ADD CONSTRAINT "FK_2ed2c984e7f481aa73869df78ff" FOREIGN KEY ("patient_id") REFERENCES "patient"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery_request" ADD CONSTRAINT "FK_de12bfe1a8a1ee96049ca63584a" FOREIGN KEY ("hospital_id") REFERENCES "hospital"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery_request" ADD CONSTRAINT "FK_c8004c3c644ad4c6fe1bd54e450" FOREIGN KEY ("health_plan_id") REFERENCES "health_plan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery_request" ADD CONSTRAINT "FK_664d5452332765c45ed1a9d2500" FOREIGN KEY ("cid_id") REFERENCES "cid"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_message" ADD CONSTRAINT "FK_634db173c52edece8dd88ea3d4c" FOREIGN KEY ("chat_id") REFERENCES "chat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_message" ADD CONSTRAINT "FK_4f402f3a2faa508ec802e1ec547" FOREIGN KEY ("sent_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat" ADD CONSTRAINT "FK_096460b01905e710c18ec0e1be7" FOREIGN KEY ("surgery_request_id") REFERENCES "surgery_request"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat" ADD CONSTRAINT "FK_15d83eb496fd7bec7368b30dbf3" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_928b7aa1754e08e1ed7052cb9d8" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD CONSTRAINT "FK_52182ffd0f785e8256f8fcb4fd6" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "default_document_clinic" ADD CONSTRAINT "FK_d8da7d7de88dde280203c3f3136" FOREIGN KEY ("doctor_id") REFERENCES "doctor_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "default_document_clinic" ADD CONSTRAINT "FK_257c4764fd51e2548e259e9e37c" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "default_document_clinic" DROP CONSTRAINT "FK_257c4764fd51e2548e259e9e37c"`);
        await queryRunner.query(`ALTER TABLE "default_document_clinic" DROP CONSTRAINT "FK_d8da7d7de88dde280203c3f3136"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP CONSTRAINT "FK_52182ffd0f785e8256f8fcb4fd6"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_928b7aa1754e08e1ed7052cb9d8"`);
        await queryRunner.query(`ALTER TABLE "chat" DROP CONSTRAINT "FK_15d83eb496fd7bec7368b30dbf3"`);
        await queryRunner.query(`ALTER TABLE "chat" DROP CONSTRAINT "FK_096460b01905e710c18ec0e1be7"`);
        await queryRunner.query(`ALTER TABLE "chat_message" DROP CONSTRAINT "FK_4f402f3a2faa508ec802e1ec547"`);
        await queryRunner.query(`ALTER TABLE "chat_message" DROP CONSTRAINT "FK_634db173c52edece8dd88ea3d4c"`);
        await queryRunner.query(`ALTER TABLE "surgery_request" DROP CONSTRAINT "FK_664d5452332765c45ed1a9d2500"`);
        await queryRunner.query(`ALTER TABLE "surgery_request" DROP CONSTRAINT "FK_c8004c3c644ad4c6fe1bd54e450"`);
        await queryRunner.query(`ALTER TABLE "surgery_request" DROP CONSTRAINT "FK_de12bfe1a8a1ee96049ca63584a"`);
        await queryRunner.query(`ALTER TABLE "surgery_request" DROP CONSTRAINT "FK_2ed2c984e7f481aa73869df78ff"`);
        await queryRunner.query(`ALTER TABLE "surgery_request" DROP CONSTRAINT "FK_345285cea966c1f78d2096e02b2"`);
        await queryRunner.query(`ALTER TABLE "surgery_request" DROP CONSTRAINT "FK_b7e705594f01025afe9cb04502c"`);
        await queryRunner.query(`ALTER TABLE "status_update" DROP CONSTRAINT "FK_f8390fe2c05188bbe4961f835b9"`);
        await queryRunner.query(`ALTER TABLE "document" DROP CONSTRAINT "FK_d8538de16919357e4cd0351d0bd"`);
        await queryRunner.query(`ALTER TABLE "document" DROP CONSTRAINT "FK_6ed807dd011acbee547ca95e5ac"`);
        await queryRunner.query(`ALTER TABLE "surgery_request_procedure" DROP CONSTRAINT "FK_5f62cc1131ccead5434ab04ddde"`);
        await queryRunner.query(`ALTER TABLE "surgery_request_procedure" DROP CONSTRAINT "FK_d9c453a21e06a38434e421ebcdc"`);
        await queryRunner.query(`ALTER TABLE "opme_item" DROP CONSTRAINT "FK_01965849109def09d33400fbd9f"`);
        await queryRunner.query(`ALTER TABLE "surgery_request_quotation" DROP CONSTRAINT "FK_75bf89ae1720acf14bd45cf11c6"`);
        await queryRunner.query(`ALTER TABLE "surgery_request_quotation" DROP CONSTRAINT "FK_c16e2628da64778fcc94054d03c"`);
        await queryRunner.query(`ALTER TABLE "patient" DROP CONSTRAINT "FK_26dc362e81bf397fdf72640df5c"`);
        await queryRunner.query(`ALTER TABLE "patient" DROP CONSTRAINT "FK_e10105a04a8a381baec6ba1fc6a"`);
        await queryRunner.query(`ALTER TABLE "recovery_code" DROP CONSTRAINT "FK_f5c95d9ca2047afa670093e2028"`);
        await queryRunner.query(`ALTER TABLE "team_member" DROP CONSTRAINT "FK_6732819d5af4c890b00358c9d54"`);
        await queryRunner.query(`ALTER TABLE "team_member" DROP CONSTRAINT "FK_229ae139290e39e857e21a15aa2"`);
        await queryRunner.query(`ALTER TABLE "doctor_profile" DROP CONSTRAINT "FK_5b83901268e3a3d2685d5bf1608"`);
        await queryRunner.query(`ALTER TABLE "team_member" DROP CONSTRAINT "UQ_356f4a7aeeb5ce1082b270ca89f"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD CONSTRAINT "UQ_user_notification_settings_user_id" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "surgery_request_procedure" ALTER COLUMN "quantity" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "procedure" ALTER COLUMN "active" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "opme_item" ALTER COLUMN "quantity" SET DEFAULT '1'`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_status_enum_old" AS ENUM('trial', 'active', 'expired', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "doctor_profile" ALTER COLUMN "subscription_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "doctor_profile" ALTER COLUMN "subscription_status" TYPE "public"."subscription_status_enum_old" USING "subscription_status"::"text"::"public"."subscription_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "doctor_profile" ALTER COLUMN "subscription_status" SET DEFAULT 'trial'`);
        await queryRunner.query(`DROP TYPE "public"."doctor_profile_subscription_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."subscription_status_enum_old" RENAME TO "subscription_status_enum"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP COLUMN "weekly_report"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP COLUMN "expiring_documents"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP COLUMN "pendencies"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP COLUMN "status_update"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP COLUMN "new_surgery_request"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP COLUMN "push_notifications"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP COLUMN "sms_notifications"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP COLUMN "email_notifications"`);
        await queryRunner.query(`ALTER TABLE "supplier" DROP COLUMN "doctor_id"`);
        await queryRunner.query(`ALTER TABLE "supplier" DROP COLUMN "is_global"`);
        await queryRunner.query(`ALTER TABLE "health_plan" DROP COLUMN "doctor_id"`);
        await queryRunner.query(`ALTER TABLE "health_plan" DROP COLUMN "is_global"`);
        await queryRunner.query(`ALTER TABLE "hospital" DROP COLUMN "doctor_id"`);
        await queryRunner.query(`ALTER TABLE "hospital" DROP COLUMN "is_global"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD "push_deadline_reminder" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD "push_new_message" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD "push_new_document" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD "push_status_change" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD "push_new_request" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD "email_deadline_reminder" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD "email_new_message" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD "email_new_document" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD "email_status_change" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD "email_new_request" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "team_member" ADD CONSTRAINT "UQ_team_member_doctor_collaborator" UNIQUE ("doctor_id", "collaborator_id")`);
        await queryRunner.query(`CREATE INDEX "IDX_user_role" ON "user" ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_email" ON "user" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_notification_read" ON "notification" ("read") `);
        await queryRunner.query(`CREATE INDEX "IDX_notification_user_id" ON "notification" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_surgery_request_created_at" ON "surgery_request" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_surgery_request_status" ON "surgery_request" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_surgery_request_patient_id" ON "surgery_request" ("patient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_surgery_request_doctor_id" ON "surgery_request" ("doctor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_patient_doctor_id" ON "patient" ("doctor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_team_member_collaborator_id" ON "team_member" ("collaborator_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_team_member_doctor_id" ON "team_member" ("doctor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_doctor_profile_user_id" ON "doctor_profile" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "default_document_clinic" ADD CONSTRAINT "FK_default_document_clinic_doctor" FOREIGN KEY ("doctor_id") REFERENCES "doctor_profile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "default_document_clinic" ADD CONSTRAINT "FK_default_document_clinic_creator" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD CONSTRAINT "FK_user_notification_settings_user" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_notification_user" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat" ADD CONSTRAINT "FK_chat_request" FOREIGN KEY ("surgery_request_id") REFERENCES "surgery_request"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat" ADD CONSTRAINT "FK_chat_user" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_message" ADD CONSTRAINT "FK_chat_message_chat" FOREIGN KEY ("chat_id") REFERENCES "chat"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_message" ADD CONSTRAINT "FK_chat_message_sender" FOREIGN KEY ("sent_by") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery_request" ADD CONSTRAINT "FK_surgery_request_doctor" FOREIGN KEY ("doctor_id") REFERENCES "doctor_profile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery_request" ADD CONSTRAINT "FK_surgery_request_created_by" FOREIGN KEY ("created_by_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery_request" ADD CONSTRAINT "FK_surgery_request_patient" FOREIGN KEY ("patient_id") REFERENCES "patient"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery_request" ADD CONSTRAINT "FK_surgery_request_hospital" FOREIGN KEY ("hospital_id") REFERENCES "hospital"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery_request" ADD CONSTRAINT "FK_surgery_request_health_plan" FOREIGN KEY ("health_plan_id") REFERENCES "health_plan"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery_request" ADD CONSTRAINT "FK_surgery_request_cid" FOREIGN KEY ("cid_id") REFERENCES "cid"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "status_update" ADD CONSTRAINT "FK_status_update_request" FOREIGN KEY ("surgery_request_id") REFERENCES "surgery_request"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document" ADD CONSTRAINT "FK_document_request" FOREIGN KEY ("surgery_request_id") REFERENCES "surgery_request"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document" ADD CONSTRAINT "FK_document_creator" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery_request_procedure" ADD CONSTRAINT "FK_surgery_request_procedure_request" FOREIGN KEY ("surgery_request_id") REFERENCES "surgery_request"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery_request_procedure" ADD CONSTRAINT "FK_surgery_request_procedure_procedure" FOREIGN KEY ("procedure_id") REFERENCES "procedure"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opme_item" ADD CONSTRAINT "FK_opme_item_request" FOREIGN KEY ("surgery_request_id") REFERENCES "surgery_request"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery_request_quotation" ADD CONSTRAINT "FK_surgery_request_quotation_request" FOREIGN KEY ("surgery_request_id") REFERENCES "surgery_request"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery_request_quotation" ADD CONSTRAINT "FK_surgery_request_quotation_supplier" FOREIGN KEY ("supplier_id") REFERENCES "supplier"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient" ADD CONSTRAINT "FK_patient_doctor" FOREIGN KEY ("doctor_id") REFERENCES "doctor_profile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient" ADD CONSTRAINT "FK_patient_health_plan" FOREIGN KEY ("health_plan_id") REFERENCES "health_plan"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recovery_code" ADD CONSTRAINT "FK_recovery_code_user" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_member" ADD CONSTRAINT "FK_team_member_doctor" FOREIGN KEY ("doctor_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_member" ADD CONSTRAINT "FK_team_member_collaborator" FOREIGN KEY ("collaborator_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctor_profile" ADD CONSTRAINT "FK_doctor_profile_user" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
