export const VISION_SUPPORTED_KINDS = [
  'surgery_request',
  'medical_report',
  'identity_document',
  'authorization_guide',
  'exam_report',
  'invoice',
  'receipt',
  'unknown',
] as const;

export const VISION_SUPPORTED_DOCUMENT_TYPES = [
  'personal_document',
  'exam_report',
  'medical_report',
  'authorization_guide',
  'invoice_protocol',
  'receipt_document',
  'contest_file',
  'additional_document',
] as const;

export const DOCUMENT_VISION_RESPONSE_SCHEMA = {
  name: 'DocumentClassificationVision',
  strict: true,
  schema: {
    type: 'object',
    additionalProperties: false,
    properties: {
      kind: {
        type: 'string',
        enum: VISION_SUPPORTED_KINDS as unknown as string[],
      },
      confidence: { type: 'number', minimum: 0, maximum: 1 },
      suggestedDocumentType: {
        type: 'string',
        enum: VISION_SUPPORTED_DOCUMENT_TYPES as unknown as string[],
      },
      ambiguity: { type: ['string', 'null'] },
      extracted: {
        type: 'object',
        additionalProperties: false,
        properties: {
          patient: {
            type: ['object', 'null'],
            additionalProperties: false,
            properties: {
              name: { type: ['string', 'null'] },
              cpf: { type: ['string', 'null'] },
              birthDate: { type: ['string', 'null'] },
              rg: { type: ['string', 'null'] },
              motherName: { type: ['string', 'null'] },
              address: { type: ['string', 'null'] },
              phone: { type: ['string', 'null'] },
            },
            required: [
              'name',
              'cpf',
              'birthDate',
              'rg',
              'motherName',
              'address',
              'phone',
            ],
          },
          hospital: { type: ['string', 'null'] },
          healthPlan: {
            type: ['object', 'null'],
            additionalProperties: false,
            properties: {
              name: { type: ['string', 'null'] },
              planId: { type: ['string', 'null'] },
              validity: { type: ['string', 'null'] },
            },
            required: ['name', 'planId', 'validity'],
          },
          tuss: {
            type: ['array', 'null'],
            items: {
              type: 'object',
              additionalProperties: false,
              properties: {
                code: { type: 'string' },
                description: { type: 'string' },
              },
              required: ['code', 'description'],
            },
          },
          cid: {
            type: ['array', 'null'],
            items: {
              type: 'object',
              additionalProperties: false,
              properties: {
                code: { type: 'string' },
              },
              required: ['code'],
            },
          },
          opme: {
            type: ['array', 'null'],
            items: {
              type: 'object',
              additionalProperties: false,
              properties: {
                description: { type: 'string' },
                qty: { type: 'number', minimum: 1 },
                supplier: { type: ['string', 'null'] },
                manufacturer: { type: ['string', 'null'] },
              },
              required: ['description', 'qty', 'supplier', 'manufacturer'],
            },
          },
          suggestedSuppliers: {
            type: ['array', 'null'],
            items: { type: 'string' },
          },
          diagnosis: { type: ['string', 'null'] },
          suggestedProcedureName: { type: ['string', 'null'] },
          laudoText: { type: ['string', 'null'] },
          notes: { type: ['string', 'null'] },
        },
        required: [
          'patient',
          'hospital',
          'healthPlan',
          'tuss',
          'cid',
          'opme',
          'suggestedSuppliers',
          'diagnosis',
          'suggestedProcedureName',
          'laudoText',
          'notes',
        ],
      },
    },
    required: [
      'kind',
      'confidence',
      'suggestedDocumentType',
      'ambiguity',
      'extracted',
    ],
  },
} as const;

export const DOCUMENT_VISION_SYSTEM_PROMPT = [
  'Você é um classificador VISUAL de documentos médicos brasileiros. Você',
  'recebe UMA imagem (laudo médico, RG/CPF, guia, exame, fatura, comprovante).',
  'Seu papel é EXTRAIR O MÁXIMO POSSÍVEL para preencher uma solicitação',
  'cirúrgica — quanto mais campos completos, menos perguntas o sistema fará',
  'ao médico depois.',
  '',
  'REGRAS GERAIS:',
  '1. Identifique `kind` entre as categorias permitidas.',
  '2. Extraia TODO campo visivelmente legível. Se está escrito, registre.',
  '3. NÃO INVENTAR — devolva `null` em vez de chutar.',
  '4. CPF/telefones/e-mails: devolva o valor cru, o backend tokeniza.',
  '5. Confiança < 0.75 → preencha `ambiguity`.',
  '',
  'COMO LER UM LAUDO/SOLICITAÇÃO CIRÚRGICA TÍPICO BR:',
  '',
  'Cabeçalho: clínica + médicos. NÃO precisa extrair CRM (o sistema já sabe',
  'quem é o médico solicitante).',
  '',
  '"Paciente: <NOME>" → `patient.name`. "Plano:" / "Convênio:" →',
  '`healthPlan.name`. "Hospital:" → `hospital`.',
  '',
  'DIAGNÓSTICO: "Diagnóstico:", "DH:", "Hipótese:" → `diagnosis` (texto',
  'livre, ex.: "Hérnia discal cervical C5-C6 com compressão radicular"). Só',
  'preencha `cid` se houver código CID escrito (ex.: "M50.1") — não invente.',
  '',
  'PROCEDIMENTO SUGERIDO: "Indicado procedimento cirúrgico com X" /',
  '"Procedimento proposto:" → `suggestedProcedureName` (nome da cirurgia,',
  'ex.: "Artrodese cervical anterior C5-C6 e C4-C5"). É o NOME, não o TUSS.',
  '',
  'TUSS: "Códigos solicitados:" / "TUSS:" — cada linha vira um item de',
  '`tuss` com `code` + `description`.',
  '',
  'OPME: "MATERIAL:" / "OPME:" — cada linha tem qty + descrição.',
  '"02 CAGES STAND ALONE" vira `{description: "CAGES STAND ALONE", qty: 2}`.',
  '',
  'FORNECEDORES: "SUGIRO AS EMPRESAS:" / "Fornecedores:" — liste nomes em',
  '`suggestedSuppliers` (ex.: ["SINTEX", "VITALITY"]). Quando houver marca',
  'entre parênteses (ex.: "SINTEX (DIVA/NOVA SPINE)"), use `opme[].manufacturer`.',
  '',
  'LAUDO CLÍNICO COMPLETO: o texto narrativo entre "Diagnóstico" e "Códigos',
  'solicitados" (queixa, exame, RNM, indicação) vai em `laudoText`, de forma',
  'objetiva e útil, limitado a ~2000 caracteres.',
  '',
  'Mapeamento `kind` → `suggestedDocumentType`:',
  '- `medical_report` / `surgery_request` → `medical_report`',
  '- `exam_report` → `exam_report`',
  '- `identity_document` → `personal_document`',
  '- `authorization_guide` → `authorization_guide`',
  '- `invoice` → `invoice_protocol`',
  '- `receipt` → `receipt_document`',
  '- `unknown` → `additional_document`',
  '',
  'IMPORTANTE: laudos cirúrgicos brasileiros (com diagnóstico + procedimento',
  'sugerido + códigos TUSS + OPME + assinatura) → classifique como',
  '`surgery_request`.',
].join('\n');
